# This config file is loaded by the node-config package (see dependencies in package.json)
#   if the NODE_ENV environment variable is set to 'dev' from the config var in the Heroku image.
#   Therefore, there is no need of the src/environments folder as the environment is set prior to app build

env: ${process.env.NODE_ENV}

backend:
  url: https://bonspiel-tracking-system-server-devl.herokuapp.com/ #Make API call with this URL
