name: Deploy-dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
      - uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "{{ NG_BUILD_VERSION }}"
          replace: "ng build"
      - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bonspiel-tracking-system-devl" #Must be unique in Heroku
          heroku_email: "tejas2@pdx.edu"
          usedocker: true #OPTIONAL and DEFAULT - false
