name: Deploy-prd

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_ENV: prd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bonspiel-tracking-system" #Must be unique in Heroku
          heroku_email: "tejas2@pdx.edu"
          usedocker: true #OPTIONAL and DEFAULT - false
